runtime: php  # language of the app
env: flex     # let app engine know we use flexible environment
runtime_config:
 document_root: public   #folder where index.php is
# Ensure we skip ".env", which is only for local development
skip_files:
 - .env #we want to skip this to make sure we don’t mess stuff up on the server
 - .git
 - .github
 - .idea
 - vendor/
env_variables:
 # Put production environment variables here.
 APP_ENV: local   # or production
 APP_DEBUG : true # or false
 APP_KEY: base64:6AVQv4RFBMY367VcY50GP7sRyeL+mA7LIiU57Mhisu4=
#go to generate app key paragraf in this tutorial
 CACHE_DRIVER: file
# instead of putting the cache in the database I recommend using redis
 SESSION_DRIVER: file #or file since both work
 APP_LOG: daily
 APP_TIMEZONE: UTC #your timezone of choice
 QUEUE_DRIVER: database #in case you execute queued jobs
# follow the part of the tutorial on setting up your SQL database
 DB_CONNECTION: mysql
 DB_HOST: 127.0.0.1
 DB_DATABASE: rezaid_admin
 DB_USERNAME: root
 DB_PASSWORD: rezaidcmsdb
 DB_SOCKET: /cloudsql/rezaidcms:us-central1:url-shortner-database-instace
 GOOGLE_VISION_PROJECT_ID : rezaidcms
#we need this for the flex environment
beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: rezaidcms:us-central1:url-shortner-database-instace
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
